image:
  # -- Image pull policy.
  pullPolicy: IfNotPresent
  # -- Image repository.
  repository: registry.k8s.io/kwok/kwok
  # -- Overrides the image tag whose default is {{ .Chart.AppVersion }}.
  tag: "v0.7.0"

# -- Image pull secrets.
imagePullSecrets: []

# -- Override the `name` of the chart.
nameOverride: ""

# -- Override the `fullname` of the chart.
fullnameOverride: ""

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
resources:
  requests:
    cpu: "10m"
  limits:
    cpu: "100m"
affinity: {}

# -- The replica count for Deployment.
replicas: 1

# -- Change `hostNetwork` to `true` if you want to deploy in a kind cluster.
hostNetwork: false
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: agentpool
          operator: In
          values:
          - user
volumes: []
env:
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
- name: HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name

volumeMounts: []
enableDeployment: true

node:
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake

  allocatable:
    cpu: 96
    memory: 1Ti
    pods: 110
    nvidia.com/gpu: "8"

  capacity:
    cpu: 96
    memory: 1Ti
    pods: 110
    nvidia.com/gpu: "8"
