apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokConfiguration
options:
  enableProfilingHandler: false
  enableContentionProfiling: false
  enablePodsOnNodeSyncListPager: false
  enablePodsOnNodeSyncStreamWatch: true
  nodeLeaseParallelism: 4
  podPlayStageParallelism: 4
  nodePlayStageParallelism: 4
  nodePort: 10247
  cidr: 10.0.0.0/12
  manageAllNodes: false
  manageNodesWithAnnotationSelector: ''
  manageNodesWithLabelSelector: ''
  manageSingleNode: ''
  nodeLeaseDurationSeconds: 40
  enableCRDs:
  - Stage
  - Metric

