name: GolangCI Lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
    - main

env:
  GO_VERSION: "1.23.0"
  GOLANGCI_VERSION: "1.58.2"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v${{ env.GOLANGCI_VERSION }}
        args: --timeout=30m --config=.golangci.yaml
